language: node_js
node_js:
  - "10"
  
stages:
  - test
  - build
  - doc
  - publish

jobs:
  include:
    - stage: test
      name: lint
      script: npm run lint
    - name: test
      script: npm run test
    - stage: build
      name: babel
      script: npm run build
    - stage: doc
      before_script: npm i -g jsdoc
      script: npm run doc
    


